### ISSUE TITLE
Implement vim's quickfix feature.

### ISSUE THREAD

**Issue by ryneeverett** [pazz/alot#1033]
This would be nice for slow operations such as receiving and indexing tasks where you want to be able to keep working but also view progress and errors.

The location-list feature might also be nice for I/O bound window-specific tasks such as sending a message, but I don't find this use case as compelling.

**Comment by pazz** [comment]
You've won the prize for the most vague feature request so far!
Please be more precise as to what it is you actually want to see implemented (of do it yourself and sens us a PR). 

Doing multiple things at once? Why don't you open multiple instances of alot in different terminals?

**Comment by ryneeverett** [comment]
> You've won the prize for the most vague feature request so far!

I have no words.

> Please be more precise as to what it is you actually want to see implemented (of do it yourself and sens us a PR).

Feature issues are often used to hash out precisely what the community wants implemented so contributors don't have to risk wasting their time or commit themselves to maintaining a hard fork into perpetuity.

> Doing multiple things at once? Why don't you open multiple instances of alot in different terminals?

You might just as well ask why vim has windows and quickfix. If you think those features are pointless I can see why you wouldn't appreciate this feature.

**Comment by dcbaker** [comment]
> Feature issues are often used to hash out precisely what the community wants implemented so contributors don't have to risk wasting their time or commit themselves to maintaining a hard fork into perpetuity.

seriously, cool your jets. The feature request is rather vague, I use vim every day for work and personal projects and I've never seen vim's quickfix. The point is that vim's quickfix doesn't seem to be useful in alot, after all, its easy enough to have multiple buffers (like vim's windows) opened at the same time, the only thing you can't do is have an editor opened and switch buffers. When you're suggest a UI feature espcailly, you need to have more than "this other, somewhat related program does this thing", please explain exactly what you're wanting, and why it's useful, because like pazz, I'm not understanding what this solves that isn't already well solved with buffers or opening a second instance of alot.

**Comment by ryneeverett** [comment]
I'm still not entirely sure if the vagueness critique is because of lack of familiarity with quickfix and how it is useful, in which case I need to explain the feature in generic terms, or because I haven't narrowed down the minimal subset of the quickfix API that would be useful in alot. I opened the issue because I figured yall would have opinions on what the API should be.

> its easy enough to have multiple buffers (like vim's windows)

I would say alot's buffers are like vim's *buffers* and as far as I can tell there is no equivalent to vim windows. You can only view one buffer at a time in alot.

> What it really sounds like, is that you have some external call that blocks and it's making alot unresponsive. Is that the case?

Yes, that is my use case. I often see vim plugins deal with this in quickfix/location windows. They're also nifty for search functionality, errors, and other temporary information displays.

If I'm the only person who wants this I could write a script that does the equivalent using my window manager and would absolutely agree with closing this. However, if this is a common problem (and I don't see how it wouldn't be) it would be better to implement it in the tui so folks don't have to reinvent the wheel. The current status seems to be total communication failure though.

**Comment by lucc** [comment]
I am sorry to say the same: I don't really understand what this feature request is about.

I use (N)vim and the quickfix/location list feature every day. Mainly to get compilation and linting error information into nvim and to search my codebase with ag. So I claim that I know the feature from vim but for me it boils down to this:
* some external process can give me information about several files+lines in my code base
* I want to see a list of that information in vim and jump from item to item (open the file at the relevant line)
* in vim I can open the (quickfix/location)list in its own vim-window (preferably a split window for me to see it at the same time as another buffer)

As a nice aside some ways to fill these list are asyncronous but that is *not* inherent to the quickfix or location list (try :grep). So in my opinion asyncronousity (is that english?) is not the core feature of the quickfix list.

So the question is how to translate these conceptrs to alot.

* Alot doesn't give you access to files and lines so how would that feature translate to alot? What kind of information would that list contain in alot?
* Alot doesn't have split windows but only buffers (as you rightly noted) so how would that list be displayed? As a notification or in another buffer?

Some more questions about your inital post:
* what kind of recieving tasks do you mean? Alot doesn't mplement any pop or imap functionality so I can not imaging what you mean.
* indexing is done by notmuch, so I also do not know what you mean here. Maybe tagging?
* as soon as I know what you mean by these things I want to ask what kind of progress you want tot see?
* for me errors are displayed as notifications. Is that different for you? What kind of errors do you need to see additionally? How would you like to see them (if not as notifications)?

And maybe a little bit of a positive answer/pointer:
* When sending alot should be still usable (while the "sending" message is shown at the bottom). I just tried it by setting sendmail to "sleep 15" in my config file and sending an email to myself. The "sending" message can be seen for 15 seconds but I can switch buffers and read mail during that time just fine.
* @dcbaker I can switch buffers in alot while I have an editor open to compose an email. I have set editor_in_thread=True and editor_spawn=True in my config.

**Comment by ryneeverett** [comment]
> As a nice aside some ways to fill these list are asyncronous but that is not inherent to the quickfix or location list (try :grep). So in my opinion asyncronousity (is that english?) is not the core feature of the quickfix list.

True, though I know of no good reason to have synchronous quickfix. If one isn't using neovim there's always tpope/vim-dispatch.

From my perspective, the core feature of quickfix as it relates to alot is that it is not a buffer but a globally visible window.

> - what kind of recieving tasks do you mean? Alot doesn't mplement any pop or imap functionality so I can not imaging what you mean.
> - indexing is done by notmuch, so I also do not know what you mean here. Maybe tagging?

offlineimap, afew, notmuch tagging, etc

> - as soon as I know what you mean by these things I want to ask what kind of progress you want tot see?

My suggestion for a minimally useful quickfix would be a (possibly temporary) globally visible window that is not in the buffer list.

> - for me errors are displayed as notifications. Is that different for you? What kind of errors do you need to see additionally? How would you like to see them (if not as notifications)?

I hadn't thought of that approach. I suppose I could pipe stderr to notify-send, though I do like seeing progress in addition to any errors that may occur.

**Comment by ryneeverett** [comment]
The use case I've emphasized is asynchronous display of output from external commands, but it would also be particularly useful for search mode:

- Could be used for searching (similar to the ag usecase @lucc mentioned). It's nice that you can keep the search list in view at the same time as the buffers you're opening, no?
- Could be used to display a search of the inbox to provide the layout and functionality of the traditional outlook/thunderbird UI.

These search mode use cases cannot be met by a separate instance of alot because it would effectively be using one instance to open a buffer in the other instance.

**Comment by lucc** [comment]
From your last comments I take it that this issue is not so much about having vim's quickfix feature but rather:

* having vim like windows in alot (or a split window that is visible in all buffers?)
* a way to retrieve information from external processes and further process and display this information inide alot. (But you should be able to do that with :call, subprocess and alot.ui.UI.notify())

Why and how do you use offlineimap/afew/notmuch from within alot? What kind of information do you need from them?

If you want to see something like an alot.buffers.SearchBuffer and like an alot.buffers.ThreadBuffer at the same time, have a look at #896 and related PRs. Maybe you can use that or expand it to suite your needs.

**Comment by ryneeverett** [comment]
While vim-like windows and splits might be nice, the use cases I've mentioned are better served by a split window that is not in the buffer list. Quickfix is visible in all buffers while location is only visible in a single buffer.

> Why and how do you use offlineimap/afew/notmuch from within alot? What kind of information do you need from them?

From my offlineimap config:

```
presynchook = ionice -c 3 chrt --idle 0 /bin/sh -c "afew --move-mails tags:inbox"
postsynchook = ionice -c 3 chrt --idle 0 /bin/sh -c "notmuch new && afew --tag --new && notmuch tag -inbox -- tag:inbox NOT folder:INBOX"
```

Viewing progress is convenient because it indicates what might be the slowdown. *Stuck on offlineimap? Must have a network problem. Stuck on afew/notmuch? Maybe I should kill some process that's hogging I/O.* I grant that this is not a critical use case or the only solution, but it mirrors the way I use quickfix for building projects in vim. *Stuck on dependency installation? Compiler errors? etc.* This pattern of having a small window displaying both progress and errors while the user can continue working is what I find the quickfix concept most useful for.
