### ISSUE TITLE
UnicodeEncodeError when starting alot

### ISSUE THREAD

**Issue by chmduquesne** [pazz/alot#673]
Hi,

I tried to start alot (current git version, installed from AUR with archlinux). I cannot get it to work: running 'alot' gets me the following stacktrace:

```
$ alot 

Traceback (most recent call last):
  File "/usr/bin/alot", line 20, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/alot/init.py", line 187, in main
    UI(dbman, cmd)
  File "/usr/lib/python2.7/site-packages/alot/ui.py", line 87, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 312, in _run
    self.draw_screen()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 563, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 1058, in render
    focus and self.focus_part == 'body')
  File "/usr/lib/python2.7/site-packages/alot/buffers.py", line 37, in render
    return self.body.render(size, focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/listbox.py", line 487, in render
    canvas = widget.render((maxcol,))
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/alot/widgets/search.py", line 168, in render
    return urwid.AttrMap.render(self, size, focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/container.py", line 2055, in render
    focus = focus and self.focus_position == i)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 1008, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/lib/python2.7/site-packages/urwid/canvas.py", line 1291, in apply_text_layout
    text[s.offs:s.end])
  File "/usr/lib/python2.7/site-packages/urwid/util.py", line 121, in apply_target_encoding
    s = s.encode( _target_encoding )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 15: ordinal not in range(128)
```

**Comment by varac** [comment]
I get the same error when I checkout 0.6 or current master (762b7dc1a60dc322876c6b5fa8769037c483eba0):

```
--- ~ » alot
Traceback (most recent call last):
  File "/home/varac/.local/bin/alot", line 11, in <module>
    load_entry_point('alot==0.7.0.dev0', 'console_scripts', 'alot')()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/buffers.py", line 39, in render
    return self.body.render(size, focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 339, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 704, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 674, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 342, in calculate_visible
    focus_widget, focus_pos = self.body.get_focus()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/walker.py", line 31, in get_focus
    return self._get_at_pos(self.focus)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/walker.py", line 64, in _get_at_pos
    widget = self._get_next_item()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/walker.py", line 77, in _get_next_item
    next_widget = self.containerclass(next_obj, **self.kwargs)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/search.py", line 28, in __init__
    self.rebuild()
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/search.py", line 148, in rebuild
    minw, maxw, align_mode)
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/search.py", line 119, in _build_part
    for t in self.thread.get_tags())
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/search.py", line 119, in <genexpr>
    for t in self.thread.get_tags())
  File "/home/varac/.local/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/globals.py", line 293, in __init__
    self.__hash = hash('{}_{}'.format(self.translated, self.txt))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2709' in position 0: ordinal not in range(128)

```

When I checkout the 0.5.1 tag and run `python setup.py install --user`, everything works again.
What more information should I provide ?

**Comment by varac** [comment]
I already checked that `~/.config/alot/config` is encoded in UTF-8 (and contains UTF-8 symbols for like `translated = ⚑`).
This is my [pip.list.txt](https://github.com/pazz/alot/files/1243005/pip.list.txt)

**Comment by dcbaker** [comment]
what's in your /etc/locale.conf and /etc/locale.gen files?

Mine look like this:
/etc/locale.conf:
```
LANG=en_US.UTF-8
```

and /etc/locale.gen:
```
en_US.UTF-8 UTF-8
en_US ISO-8859-1
```

**Comment by dcbaker** [comment]
oh wait. That stack trace should not be present on 0.6, the patch that added that bug was added after 0.6; it was fixed by lucc and I merged that a couple of hours ago, so master *should* be working now.

**Comment by varac** [comment]
@dcbaker Awesome, a git pull from master did it! Now everything is fine again.

**Comment by dcbaker** [comment]
glad to hear it. I maintain that package in the aur, but I haven't pulled an update yet today so I didn't notice :/

**Comment by three-comrades** [comment]
What is the current idea here, should alot work irrespectively of `LANG`? Even with `LANG=C`? Because currently it doesn't :-) (e.g.: `LANG=C alot`, `:search ö` immediately results in a hard crash somewhere in urwid).

**Comment by pazz** [comment]
Quoting Julian Mehne (2018-01-10 12:04:45)
> What is the current idea here, should alot work irrespectively of LANG? Even
> with LANG=C? Because currently it doesn't :-) (e.g.: LANG=C alot, :search ö
> immediately results in a hard crash somewhere in urwid).

Yes it should. And it does for me. I even get the expected result set
when doing that search for "ö" (but still see the exception related to
storing the command history).

**Comment by three-comrades** [comment]
> I even get the expected result set when doing that search for "ö"

Weird. For me it turns out it's even enough to just start alot and type 'ö' or to even just copy it with `ctrl+shift+v:
- `LANG=C alot -l log -d debug`
- type 'ö' (or `ctrl+shift+v` an ö)
- hard crash:
```
LANG=C alot
Traceback (most recent call last):
  File "/home/kelvin/tmp/alot/venv/bin/alot", line 11, in <module>
    load_entry_point('alot==0.7.0.dev0', 'console_scripts', 'alot')()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 400, in _update
    keys = self.input_filter(keys, raw)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 539, in input_filter
    return self._input_filter(keys, raw)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 189, in _input_filter
    prefix=keyseq)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/settings/manager.py", line 356, in get_mapped_input_keysequences
    cand = [c for c in candidates if c.startswith(prefixes)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
There's nothing logged after `DEBUG:ui:Got key (['\xc3', '\xb6'], [195, 182])`

Alternatively, I get this error when doing the search:
- `LANG=C alot -l log -d debug`
- `:search ö` (no pressing enter)
- hard crash:

```
LANG=C alot -l log -d debug
Traceback (most recent call last):
  File "/home/kelvin/tmp/alot/venv/bin/alot", line 11, in <module>
    load_entry_point('alot==0.7.0.dev0', 'console_scripts', 'alot')()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/__main__.py", line 130, in main
    UI(dbman, cmdstring)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 124, in __init__
    self.mainloop.run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 1200, in wrapper
    rval = f(*args,**kargs)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/widgets/globals.py", line 211, in keypress
    result = urwid.Edit.keypress(self, size, key)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/widget.py", line 1474, in keypress
    self.insert_text(key)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/widget.py", line 1398, in insert_text
    text = self._normalize_to_caption(text)
  File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/widget.py", line 1415, in _normalize_to_caption
    return text.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

The log:
```
DEBUG:ui:Got key (['o'], [111])
DEBUG:ui:cmdline: 'prompt 'search ''
DEBUG:ui:search command string: "prompt 'search '"
DEBUG:__init__:mode:search got commandline "prompt 'search '"
DEBUG:__init__:ARGS: [u'prompt', u'search ']
DEBUG:__init__:cmd parms {'startwith': u'search '}
INFO:globals:open command shell
DEBUG:ui:Got key (['\xc3', '\xb6'], [195, 182])
```

**Comment by three-comrades** [comment]
For the first crash:
- in my config:
```
[bindings]
    S = toggletags spam
```
- LANG=C alot
- type/ctrl-v `ö` -> crash

The relevant code is [here](https://github.com/pazz/alot/blob/d94d786b296d0f746e0442d9c3483673dec2e38b/alot/settings/manager.py#L350). ConfigObj ends up reading the binding from the config file as unicode, such that  `c=u'S'`. But `prefix`, the `ö` we've typed, is a binary string. `u'foo'.startswith('ö')` results in the observed crash.

Forcing urwid to use unicode fixes both crashes (see the linked commit), but I don't completely understand the implications.

**Comment by pazz** [comment]
@three-comrades: Although I cannot reproduce this, I see no harm in your patch. Can you send it as PR to give others a while to respont? I will merge it in before the upcoming release..

**Comment by lucc** [comment]
close?

**Comment by three-comrades** [comment]
> close?

I think so - the originally reported crash seems to be fixed, as well as the `LANG=C` crash I encountered.
